# [default_session]
# startup_script = "~/.config/sesh/startup_script.sh"

[[session]]
name = "Dotfiles"
path = "~/dotfiles"
startup_command = "nvim ."

[[session]]
name = "Database"
path = "~/tools/dbui"
startup_command = "nvim -c ':DBUIToggle'"

[[session]]
name = "sml dev"
path = "~/code/sml/dev"
# startup_script = "tmuxp load -a ~/.tmuxp/sml.yaml"
# startup_command = "tmuxp load -a ~/.tmuxp/sml.yaml"

[[session]]
name = "sml review"
path = "~/code/sml/review"

[[session]]
name = "hlb"
path = "~/code/hlb-ws-app/dev"

[[session]]
name = "sml-infra"
path = "~/code/sml-infra/dev"

[[session]]
name = "Portal"
path = "~/code/sml-portal/dev"

[[session]]
name = "gbm"
path = "~/code/gbm"

[[session]]
name = "http"
path = "~/code/http"
startup_command = "nvim ."

[[session]]
name = "ghostty"
path = "~/.config/ghostty"
startup_command = "nvim ."

[[session]]
name = "nvim"
path = "~/.config/nvim"
startup_command = "nvim ."

[[session]]
name = "tmux"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "sesh"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "nix-darwin"
path = "~/.config/nix-darwin"
startup_command = "nvim ."

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "notes"
path = "~/code/notes"
startup_command = "nvim ."

[[session]]
name = "rms-pi-01"
startup_command = "ssh rms@rms-pi-01"

[[session]]
name = "pnp"
path = "~/code/pnpcore"
